#!/usr/bin/env python3
"""related-links.py — three STATIC related-post links in every post. Idempotent.

Why (2026-09-03, todo/agentgrow-blog-traffic-recovery.md Phase 3b): every post's
body carried exactly one internal link (the trial CTA). The "More from the blog"
block was filled in the browser by a fetch of posts-data.json — and not with
related posts, with the three NEWEST — so a crawler saw an empty <div> and the
28 posts published after March had no inbound link from anywhere but the
sitemap. This writes real <a> tags into that block, picked by topic overlap, and
removes the fetch script that would overwrite them.

Picking: tokens from title + slug + tags, canonicalised (smb/smbs, b2b, plural
stripping, stop-words), Jaccard overlap, +0.15 for the same category, ties by
newest date. Deterministic — the same corpus always yields the same links.
Candidates = the entries in docs/posts-data.json (redirect stubs and, once Phase
2 lands, canonicalised/noindexed posts are already absent from it).

Usage:
  python3 docs/scripts/related-links.py docs/posts/<slug>.html   # one post (the gate)
  python3 docs/scripts/related-links.py --all                    # backfill
  add --check to report without writing (exit 1 if anything would change)
"""
import json
import re
import sys
from html import escape
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent
POSTS = DOCS / "posts"
DATA = DOCS / "posts-data.json"
N_RELATED = 3

STOP = set("""a an the for to of and in with your you how what why is are on by vs from at
as it that this be can 2026 2025 ai agent agents guide complete actually without
small business businesses india indian b2b smb founder founders service services
firm firms company companies""".split())
CANON = {"smbs": "smb", "b2c": "b2c", "linkedin": "linkedin", "emails": "email",
         "leads": "lead", "agencies": "agency", "campaigns": "campaign"}

BADGE_CLASS = {"Platform": "badge-platform", "Getting Started": "badge-getting-started",
               "How-To": "badge-how-to", "Strategy": "badge-strategy"}

# The empty grid the shell emits (filled by JS at runtime). Cards nest <div>s,
# so once filled the block can only be re-found by its own markers — never by
# a non-greedy `.*?</div>` (that stops inside the first card and mangles it).
EMPTY_GRID_RE = re.compile(r'(<div class="card-grid" id="related-posts">)\s*(</div>)', re.S)
FETCH_SCRIPT_RE = re.compile(r"\s*<script>\s*fetch\('\.\./posts-data\.json'\).*?</script>", re.S)
MARK = "<!-- related: generated by related-links.py -->"
END_MARK = "<!-- /related -->"
BLOCK_RE = re.compile(re.escape(MARK) + r".*?" + re.escape(END_MARK), re.S)


def _norm(w):
    w = CANON.get(w, w)
    if w.endswith("s") and not w.endswith("ss") and len(w) > 4:
        w = w[:-1]
    return w


def tokens(entry):
    """Weighted bag: title + slug + tags count double, excerpt once."""
    strong = " ".join([entry.get("title", ""), entry.get("slug", "").replace("-", " "),
                       " ".join(entry.get("tags", []) or [])]).lower()
    weak = (entry.get("excerpt") or entry.get("description") or "").lower()
    out = {}
    for text, wt in ((strong, 2.0), (weak, 1.0)):
        for w in re.findall(r"[a-z0-9]+", text):
            if w in STOP or len(w) < 3:
                continue
            w = _norm(w)
            out[w] = max(out.get(w, 0.0), wt)
    return out


def weighted_jaccard(a, b):
    keys = set(a) | set(b)
    if not keys:
        return 0.0
    inter = sum(min(a.get(k, 0.0), b.get(k, 0.0)) for k in keys)
    union = sum(max(a.get(k, 0.0), b.get(k, 0.0)) for k in keys)
    return inter / union


def entry_from_html(path: Path):
    """A minimal entry for a post not yet in posts-data.json (the gate runs
    before regenerate_indexes.py): title, meta description, badge category."""
    html = path.read_text(encoding="utf-8")
    m = re.search(r"<title>(.*?)</title>", html, re.S)
    title = re.sub(r"\s*[—–-]\s*AgentGrow.*$", "", m.group(1).strip()) if m else path.stem
    d = re.search(r'name="description" content="([^"]*)"', html)
    c = re.search(r'<span class="badge[^"]*">([^<]+)</span>', html)
    return {"slug": path.stem, "title": title, "excerpt": d.group(1) if d else "",
            "category": c.group(1).strip() if c else "", "tags": []}


def pick_related(slug, entries, fallback=None):
    me = next((e for e in entries if e["slug"] == slug), None) or fallback
    if not me:
        return []
    mine = tokens(me)
    scored = []
    for e in entries:
        if e["slug"] == slug:
            continue
        j = weighted_jaccard(mine, tokens(e))
        if e.get("category") == me.get("category"):
            j += 0.03
        scored.append((-j, e.get("date", ""), e))
    scored.sort(key=lambda x: (x[0], x[1] and -int(x[1].replace("-", "") or 0)))
    return [e for _, _, e in scored[:N_RELATED]]


def card(e):
    cls = BADGE_CLASS.get(e.get("category", ""), "")
    badge = f'<span class="badge {cls}">' if cls else '<span class="badge">'
    return ('<div class="card">'
            f'{badge}{escape(e.get("category", ""))}</span>'
            f'<h2><a href="{e["slug"]}.html">{escape(e["title"])}</a></h2>'
            f'<p class="excerpt">{escape(e.get("excerpt", ""))}</p>'
            f'<div class="card-meta"><span>{escape(e.get("publishedAt", ""))}</span>'
            f'<span>&middot;</span><span>{escape(e.get("readTime", ""))}</span></div>'
            '</div>')


def apply(path: Path, entries, check=False):
    html = path.read_text(encoding="utf-8")
    if 'http-equiv="refresh"' in html[:600].lower():
        return "stub"
    if 'id="related-posts"' not in html:
        return "no-block"
    related = pick_related(path.stem, entries, fallback=entry_from_html(path))
    if not related:
        return "not-in-data"
    block = MARK + "\n" + "\n".join(card(e) for e in related) + "\n" + END_MARK
    if MARK in html and END_MARK in html:
        new = BLOCK_RE.sub(lambda m: block, html, count=1)
    elif EMPTY_GRID_RE.search(html):
        new = EMPTY_GRID_RE.sub(lambda m: m.group(1) + "\n" + block + "\n" + m.group(2), html, count=1)
    else:
        return "no-block"
    new = FETCH_SCRIPT_RE.sub("", new, count=1)
    if new == html:
        return "unchanged"
    if not check:
        path.write_text(new, encoding="utf-8")
    return "changed"


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    entries = json.loads(DATA.read_text(encoding="utf-8"))
    targets = sorted(POSTS.glob("*.html")) if "--all" in sys.argv else [Path(a) for a in args]
    if not targets:
        print(__doc__)
        return 2
    counts = {}
    for t in targets:
        r = apply(t, entries, check)
        counts[r] = counts.get(r, 0) + 1
        if r in ("no-block", "not-in-data"):
            print(f"  SKIP  {t.name}: {r}", file=sys.stderr)
    verb = "would change" if check else "changed"
    print(f"related-links: {verb} {counts.get('changed', 0)}, unchanged {counts.get('unchanged', 0)}, "
          f"stubs {counts.get('stub', 0)}, skipped {counts.get('no-block', 0) + counts.get('not-in-data', 0)}")
    return 1 if (check and counts.get("changed")) else 0


if __name__ == "__main__":
    sys.exit(main())
